#include "ParserWrapper.h"

#include <cerrno>
#include <sstream>
#include <stdexcept>

// Autogenerated files are not super strict.
#pragma GCC diagnostic ignored "-Weffc++"
#include "Parser.h"
#include "Lexer.h"

namespace ifpp {

void parse(Context & ctx, Logger & log, bool debugLex = false, bool debugParse = false) {
	if (!(yyin = fopen(ctx.file.c_str(), "r"))) {
		std::stringstream ss;
		ss << "Unable to open input file \"" << ctx.file << "\"!" << std::endl;
		ss << "Reason: " << strerror(errno);
		throw std::runtime_error(ss.str());
	}
	
	yy::Parser parser(ctx);
	
	yyset_debug(debugLex);
	parser.set_debug_level(debugParse);
	
	log.message() << "Parser initialized." << std::endl;
	log.message() << "Parsing file \"" << ctx.file << "\"..." << std::endl;
	
	int result = parser.parse();
	fclose(yyin);
	
	if (result != 0) throw std::runtime_error("Parser finished with an error.");
}

}